--- #YAML:1.0
name:               MojoX-Run
version:            0.15
abstract:           asynchronous external command and subroutine execution for Mojo
author:
    - "Brane F. Gracnar" <"bfg@frost.ath.cx">
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:  0.99994
    Storable:     0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
